[tool.poetry]
name = "goroam"
version = "0.1.0"
description = ""
authors = ["r-fynn <78019261+r-fynn@users.noreply.github.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.12"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
